In [2]:
import numpy as np
import torch

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_ones = torch.ones_like(x_data)
#retains the property of x_data
print(f"Ones tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data,dtype = torch.float)
#overrides the data type of x_data
print(f"Random tensor: \n {x_rand} \n")

Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random tensor: 
 tensor([[0.3571, 0.8289],
        [0.1802, 0.8078]]) 



In [6]:
shape = (2,3)
rand_tensor = torch.rand(shape)
zero_tensor = torch.rand(shape)
ones_tensor = torch.rand(shape)

print(f"Rand tensor: \n {rand_tensor} \n")
print(f"Zero tensor: \n {zero_tensor} \n")
print(f"Ones tensor: \n {ones_tensor} \n")

Rand tensor: 
 tensor([[0.9063, 0.7618, 0.3232],
        [0.7850, 0.3905, 0.9611]]) 

Zero tensor: 
 tensor([[0.4586, 0.8794, 0.1142],
        [0.7068, 0.3104, 0.8435]]) 

Ones tensor: 
 tensor([[0.8924, 0.0741, 0.5877],
        [0.3666, 0.3319, 0.0462]]) 



In [4]:
tensor = torch.rand(2,3)

In [5]:
if torch.accelerator.is_available:
  tensor = tensor.to(torch.accelerator.current_accelerator())

In [7]:
tensor = torch.ones(4,4)
print(f"First Row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[:,-1]}")
tensor[:,1] = 0
print(tensor)

First Row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [8]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [10]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = tensor*tensor.T
print(y1)
print(y2)
print(y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [12]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
